APP_BASE is already defined (#86)
Defining it again causes:
```
Error: UPGRADE FAILED: The order in patch list:
[map[value:.....]]
 doesn't match $setElementOrder list:
[map[value:.....]]
```